service: fastspring-native-poc

variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: nodejs22.x
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 'dynamodb:*'
          Resource: '*'
  environment:
    PEM_PRIVATE_KEY: ${ssm:pem-private-key}
    JWT_MY_SECRET: ${ssm:jwt-my-secret}
    DYNAMODB_LOGIN_TABLE: loginTable
    DYNAMODB_SUBSCRIPTION_TABLE: subscriptionTable

plugins:
  - serverless-plugin-typescript

functions:
  login:
    handler: app/handler/login.handler
    events:
      - http:
          path: login
          method: post
          cors: true

  postback:
    handler: app/handler/webhook.handler
    events:
      - http:
          path: webhook
          method: post
          cors: true

  encode:
    handler: app/handler/encode.handler
    events:
      - http:
          path: encode
          method: post
          cors: true

  getSubscription:
    handler: app/handler/getSubscription.handler
    events:
      - http:
          path: getSubscription
          method: post
          cors: true

resources:
  Resources:
    loginTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: loginTable
        AttributeDefinitions:
          - AttributeName: deviceId
            AttributeType: S
        KeySchema:
          - AttributeName: deviceId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    playerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: subscriptionTable
        AttributeDefinitions:
          - AttributeName: playerId
            AttributeType: S
          - AttributeName: subscriptionId
            AttributeType: S
        KeySchema:
          - AttributeName: playerId
            KeyType: HASH
          - AttributeName: subscriptionId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST