import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
    paddingTop: 0,
  },
  loadingContainer: {
    flex: 1,
    backgroundColor: '#f5f5f5',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 20,
    fontSize: 16,
    color: '#666',
  },
  topMenuContainer: {
    backgroundColor: '#1a2332',
  },
  topMenu: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#1a2332',
    paddingHorizontal: 15,
    paddingVertical: 12,
    width: '100%',
  },
  logo: {
    width: 80,
    height: 40,
  },
  currencyCounter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
  },
  coinIcon: {
    width: 20,
    height: 20,
    marginRight: 5,
  },
  currencyText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  rightIcons: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconButton: {
    marginLeft: 15,
    padding: 5,
  },
  icon: {
    width: 28,
    height: 28,
  },
  scrollContent: {
    flex: 1,
  },
  scrollContentContainer: {
    paddingHorizontal: 5,
    paddingVertical: 5,
    alignItems: 'center',
  },
  bigImage: {
    width: '100%',
    height: 300,
    borderRadius: 15,
    marginBottom: 20,
    backgroundColor: '#ddd',
  },
  button: {
    width: '100%',
    height: 60,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
    overflow: 'hidden',
  },
  buttonBackground: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    borderRadius: 15,
  },
  buttonText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
    zIndex: 1,
  },
  // User Badge Styles
  userBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
    marginLeft: 10,
  },
  userCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    marginRight: 8,
    borderWidth: 1,
    borderColor: '#fff',
  },
  userText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  // Subscription Mode Styles
  logoContainer: {
    width: '100%',
    backgroundColor: '#fff',
    borderRadius: 15,
    padding: 40,
    marginBottom: 20,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    minHeight: 150,
  },
  logoPlaceholder: {
    fontSize: 48,
    fontWeight: 'bold',
    color: '#1a2332',
    marginBottom: 10,
  },
  logoSubtext: {
    fontSize: 14,
    color: '#666',
  },
  subscriptionCard: {
    width: '100%',
    backgroundColor: '#fff',
    borderRadius: 15,
    padding: 30,
    marginBottom: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  subscriptionInfo: {
    alignItems: 'center',
  },
  subscriptionTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#1a2332',
    marginBottom: 5,
    textAlign: 'center',
  },
  subscriptionPrice: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#1a2332',
    marginTop: 15,
  },
  sectionCard: {
    width: '100%',
    backgroundColor: '#fff',
    borderRadius: 15,
    padding: 20,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1a2332',
    marginBottom: 15,
  },
  listItem: {
    paddingVertical: 12,
  },
  listItemText: {
    fontSize: 16,
    color: '#333',
  },
  divider: {
    height: 1,
    backgroundColor: '#e0e0e0',
  },
  featureRow: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    marginBottom: 15,
  },
  featureCard: {
    width: '48%',
    backgroundColor: '#1a2332',
    borderRadius: 15,
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 100,
  },
  featureTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#fff',
    textAlign: 'center',
  },
  offerCard: {
    width: '100%',
    backgroundColor: '#fff',
    borderRadius: 15,
    padding: 20,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  offerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1a2332',
    marginBottom: 5,
  },
  offerSubtitle: {
    fontSize: 14,
    color: '#666',
    marginBottom: 15,
  },
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  halfButton: {
    width: '48%',
    backgroundColor: '#f5e6d3',
    borderRadius: 10,
    padding: 15,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#d4b896',
  },
  halfButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1a2332',
    textAlign: 'center',
  },
  halfButtonSubtext: {
    fontSize: 11,
    color: '#666',
    textAlign: 'center',
  },
  toggleButton: {
    width: '100%',
    backgroundColor: '#666',
    borderRadius: 15,
    padding: 15,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  toggleButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  playerIdContainer: {
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
    paddingVertical: 8,
    paddingHorizontal: 15,
    alignItems: 'flex-start',
    borderTopWidth: 1,
    borderTopColor: 'rgba(0, 0, 0, 0.1)',
  },
  playerIdRow: {
    flexDirection: 'row',
    width: '100%',
  },
  playerIdLabel: {
    fontSize: 11,
    color: '#666',
    fontFamily: 'Courier',
    width: 105,
  },
  playerIdValue: {
    fontSize: 11,
    color: '#666',
    fontFamily: 'Courier',
    flex: 1,
  },
});
